### ISSUE TITLE
(JSONDecodeError) radarr_add_from_list.py

### ISSUE THREAD

**Issue by bison529** [sirk123au/ArrTools#19]
Hi,

when run command $python3 radarr_add_from_list.py movielist.csv

showing this error:

```
[INFO] Downloading Radarr Movie Data. :)
Traceback (most recent call last):
  File "radarr_add_from_list.py", line 253, in <module>
    main()
  File "radarr_add_from_list.py", line 235, in main
    RadarrData = json.loads(rsp.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I using Radarr in dokcer, this config.ini details (API are hid):

```
[radarr]
api_key = API Key
baseurl = https://radarr.domian.xyz/
urlbase =
rootfolderpath = /Movies/Movies_Hollywood
searchForMovie = False
qualityProfileId = 1
omdbapi_key = API Key; sign up here for api key http://www.omdbapi.com/apikey.aspx

 Standard Profile ID
 1 Any
 2 Bluray
 3 HD-1080p
 4 HD-720p
 5 SD
 6 Ultra-HD
 7 WEB-DL 1080P
```

I have tried localhost:7878 and IP Address docker network (172.18.0.25:7878) as same result.

**Comment by tom-dell** [comment]
I'm having this issue too, it's also happening in the sonarr version.

**Comment by dp247** [comment]
I'd download the new file and try again. I just ran through no issue :)

**Comment by sirk123au** [comment]
Download again and it should all work
