### ISSUE TITLE
API Error in Adding Movies

### ISSUE THREAD

**Issue by thetechnocore** [sirk123au/ArrTools#4]
Hi

Please close if I should be posting this in a Radaar issue list.  I'm using your scripts to import files from a CSV file.  After a mighty battle :)  I've almost got it working, but my test run finds a movie but does not add it to Radaar.  This is the debug output in Radaar logging.  Adding movies via the GUI UI works fine.  

Grateful for any support or guidance. 

[v0.2.0.1504] Newtonsoft.Json.JsonReaderException: Could not convert string to boolean: N. Path 'addOptions.searchForMovie', line 1, position 339.
   at Newtonsoft.Json.JsonReader.ReadBooleanString(String s)
   at Newtonsoft.Json.JsonTextReader.ReadAsBoolean()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at NzbDrone.Api.Extensions.ReqResExtensions.FromJson(Stream body, Type type) in C:\projects\radarr-usby1\src\NzbDrone.Api\Extensions\ReqResExtensions.cs:line 31
   at NzbDrone.Api.Extensions.ReqResExtensions.FromJson[T](Stream body, Type type) in C:\projects\radarr-usby1\src\NzbDrone.Api\Extensions\ReqResExtensions.cs:line 24
   at NzbDrone.Api.Extensions.ReqResExtensions.FromJson[T](Stream body) in C:\projects\radarr-usby1\src\NzbDrone.Api\Extensions\ReqResExtensions.cs:line 19
   at NzbDrone.Api.REST.RestModule`1.ReadResourceFromRequest(Boolean skipValidate) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 194
   at NzbDrone.Api.REST.RestModule`1.<set_CreateResource>b__41_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 161
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by sirk123au** [comment]
is your config correct make sure that you have searchForMovie = True|False in config

**Comment by thetechnocore** [comment]
> is your config correct make sure that you have searchForMovie = True|False in config

Thanks - will take a look and report back.

**Comment by sirk123au** [comment]
I have made some changes so if you pull the latest it should work now

**Comment by thetechnocore** [comment]
Apologies not had a chance to look at this - will get some time over the weekend fingers crossed.  Thank you for the quick reply
