### ISSUE TITLE
[Error] JSONDecodeError

### ISSUE THREAD

**Issue by Ashish0804** [sirk123au/ArrTools#6]
Traceback (most recent call last):
  File "radarr_add_from_list.py", line 236, in <module>
    main()
  File "radarr_add_from_list.py", line 220, in main
    RadarrData = json.loads(rsp.text)
  File "/home/ashish/miniconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/ashish/miniconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ashish/miniconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Config

[radarr]
api_key = KEY
baseurl = localhost:7878/radarr
urlbase = ; Include URL Base if you have it enabled
rootfolderpath = '/home/ashish/HDD/Torrents/completed/'
searchForMovie = True
qualityProfileId = 7
omdbapi_key = KEY; sign up here for api key http://www.omdbapi.com/apikey.aspx

**Comment by Ashish0804** [comment]
api_key and omdb api keys are dummy here.

**Comment by sirk123au** [comment]
check you urlbase and baseurl are correct

**Comment by sirk123au** [comment]
have you got any movies in radarr yet?

**Comment by Ashish0804** [comment]
> check you urlbase and baseurl are correct

Hi
the baseurl is correct as i have tried the code with postman and i get 200 success code. As with urlbase, i don't have it enabled in the radarr settings so i have left it empty in the config.

**Comment by sirk123au** [comment]
baseurl = localhost:7878/radarr this is wrong in the config it should be 

baseurl = localhost:7878

I don't think it is receiving the correct data to parse

**Comment by Ashish0804** [comment]
> localhost:7878

results in this

Traceback (most recent call last):
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/requests/models.py", line 380, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/urllib3/util/url.py", line 392, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: http://localhost:7878; Include URL Base if you have it enabled/api/movie

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "radarr_add_from_list.py", line 236, in <module>
    main()
  File "radarr_add_from_list.py", line 218, in main
    rsp = requests.get(url , headers=headers)
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/requests/sessions.py", line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/requests/models.py", line 382, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: http://localhost:7878; Include URL Base if you have it enabled/api/movie

**Comment by sirk123au** [comment]
Can you try with ipaddress:port in your config

**Comment by bison529** [comment]
Hi,

sorry for re-open this topic, but I am facing same issue.
when run command $python3 radarr_add_from_list.py movielist.csv

showing this error:

```
[INFO] Downloading Radarr Movie Data. :)
Traceback (most recent call last):
  File "radarr_add_from_list.py", line 253, in <module>
    main()
  File "radarr_add_from_list.py", line 235, in main
    RadarrData = json.loads(rsp.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I using Radarr in dokcer, this config.ini details (API are hid):

```
[radarr]
api_key = API Key
baseurl = https://radarr.domian.xyz/
urlbase =
rootfolderpath = /Movies/Movies_Hollywood
searchForMovie = False
qualityProfileId = 1
omdbapi_key = API Key; sign up here for api key http://www.omdbapi.com/apikey.aspx

 Standard Profile ID
 1 Any
 2 Bluray
 3 HD-1080p
 4 HD-720p
 5 SD
 6 Ultra-HD
 7 WEB-DL 1080P
```

I have tried localhost:7878 and IP Address docker network (172.18.0.25:7878) as same result.
